### ISSUE TITLE
아이템 구현 

### ISSUE THREAD

**Issue by meungenie** [MeungGenie/SEProject#12]
**줄 삭제 아이템**
- 기본블럭 중 한 칸이 문자 'L'로 변경.
- 'L'의 등장위치는 무작위
- 블럭이 더 이상 움직이지 못하게 되면(바닥이나 다른 블럭에 닿으면 L이 위치한 줄은 해당 줄이 꽉 차 있지 않아도 삭제

**십자가 삭제 아이템**
- 기본블럭 중 한 칸이 문자 'C'로 변경.
- 'C'의 등장위치는 무작위
- 블럭이 더 이상 움직이지 못하게 되면(바닥이나 다른 블럭에 닿으면 'C'가 위치한 가로와 세로 한 줄은 해당 줄이 꽉 차 있지 않아도 삭제

**무게추 아이템**
- 'O' 모양의 너비가 4칸
- 회전 불가
- 떨어지면서 밑에 있는 모든 블럭들을 지움
- 바닥이나 다른 블럭에 닿으면 더 이상 좌우이동 불가

**한 칸 블록 아이템**
- 한 칸 짜리 '●' 모양
- 기존 블록과 동일하게 작동

**회전 불가 블럭**
- 기존 블럭 모양과 동일하지만 '×'로 표시
- 처음 나온 형태에서 회전 불가

**Comment by sonemelody** [comment]
7f28e1d8128a896acd99bf2d6fa9ada113f2ce1c 한 칸 블록 아이템, 회전 불가 블럭 구현 완료.

**Comment by meungenie** [comment]
62f5be375046dbd8506947414e2ded6941fce227
무게추, 라인삭제, 십자가 삭제 아이템 구현 완료
