### ISSUE TITLE
블럭이 삐뚤빼뚤하게 쌓인다

### ISSUE THREAD

**Issue by ShinYoung-Kim** [MeungGenie/SEProject#46]
착시인지 진짜 삐뚤빼뚤한건지도 모르겠다

**Comment by ShinYoung-Kim** [comment]
![image](https://user-images.githubusercontent.com/83866983/169964565-6f8ee9b6-08ad-47a7-ae1c-74d57e520ede.png)

**Comment by sonemelody** [comment]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/49124725/170512799-51c588c6-5c93-4c9a-ada8-16a0a22549a2.png">
삐뚤빼뚤해보이지만 실제로 확대해서 픽셀로 확인해보면
 
![image](https://user-images.githubusercontent.com/49124725/170513005-42efed02-c6dc-40ed-9801-96300a68a224.png)
올바르게 정렬되어 있다
