### ISSUE TITLE
블록 이동 시, 벽에 닿았을때(?) 오류

### ISSUE THREAD

**Issue by ss021o** [MeungGenie/SEProject#8]
![image](https://user-images.githubusercontent.com/49343360/164168175-9b0ac79e-8863-403c-8c92-a0e6cef36b71.png)

에러문구 : Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 10

현상 : 키보드를 누르는 이벤트 값이 안먹고, 게임 자체가 종료됨

**Comment by meungenie** [comment]
0ed997d4b001f9b12ba6cb8c3ce777146559cd6d
회전 개선, 회전블록이 충돌할 경우 자리를 이동해 회전하도록 구현.
